# [JAVA]

- 학습 일시 : 2019-11-01
- 개요
  - NullPointerException
  - 속성변수와 참조변수
  - 예외 (Exception)
  - 예외 처리
  - try ~ catch 문
  - 예외 종류
  - 사용자정의 예외
  - Problems

---

<br>

### 1) NullPointerException

- `null` : 메모리가 할당되지 않음을 의미

- `NullPointerException` : 메모리 할당을 하지 않은 상태에서 필드 또는 메소드를 참조했을 때 발생하는 에러

  > null . 필드명
  >
  > null . 메소드명()

- ```java
  class A{
    void hello(){}
  }
     
  class Test{
    A a;//null
        
    void print(){
      //a.hello();  ====> null.hello();   ===> NullPointerException발생
      a = new A(); //a에는 메모리 주소정보가 저장
      a.hello();  ====> 실행OK 
    }
    
    public static void main(String []args){
      Test t = new Test();
      t.print();
    }
  }
  ```

<br>

### 2) 속성변수와 참조변수

<br>

### 3) 예외 (Exception)

- 프로그램 실행 중 발생하는 예기치 않은 사건

  - 발생하는 모든 예외를 객체 취급
  - 예외 관련 클래스를 제공

- 예시

  - 정수를 0으로 나누는 경우

  - 배열의 첨자가 음수값 혹은 배열의 크기를 벗어나는 경우

  - 부적절한 형변환이 일어나는 경우

    ```java
    int su = 3.14;	// 에러
    int su = (int)3.14;
    
    double d = 30;	// 묵시적 형변환
    double d = (double)30;	// 명시적 형변환
    
    (int)"홍길동"	// 에러
    (B)A		  // 에러 : 상속관계 없음    
    ```

  - 입출력시 인터럽트가 발생하는 경우

  - 입출력하기 위해 지정한 파일이 존재하지 않거나 파일이 틀린 경우

- 기본 예외 상황 처리기

  - 프로그램 --- 실행 --- > 예외발생
  - JVM : 예외 발생 시 관련된 예외 클래스로부터 예외 객체 생성. 프로그램에서 지정된 예외처리 루틴에게 전달

- Exception 클래스 계층 구조

  - `java.lang.Object`
    - `java.lang.Throwable`
      - `Error` : 하드디스크 포맷이 망가진 경우, 메모리 파괴, 스택오버플로우, ... (프로그램 처리하지 않고, JVM에게 맡겨주는 것이 일반적)
      - `Exception`

<br>

### 4) 예외 처리

- 예외처리

  - 예외가 발생시 어떤 대응을 할지 작성하는 추가 코드
  - 자바 언어를 더욱 강하게(robust) 만드는 요소
  - 개발자 입장 : 코드량 증가
  - 사용자 입장 : 신뢰성 증가

- throws : 예외 처리 전가

  - `hello()`메소드를 호출하는 메소드에서 예외처리 해줘!

  ```java
  void hello() throws Exception
  {
      문장 1;
      문장 2;
      문장 3;
  }
  ```


<br>

### 5) try ~ catch 문

> try{
>
> ​	예외가 발생할 가능성이 있는 문장; (대체적으로 메소드 호출 문장)
>
> } cahtch (예외타입 변수명){
>
> ​		실제 예외 발생시 처리할 문장;
>
> } finally{
>
> ​		예외 발생과 상관없이 반드시 실행할 문장;
>
> }

- 개별 처리

  ```java
  void hello() throws Exception
  {
      try{
        AException 가능성 문장;
      } catch(AException e){
          AException 발생 시 실행 문장;
      } 
      try{
      	BException 가능성 문장;
      } catch(BException e){
          BException 발생 시 실행 문장;
      }	
      try{
      	CException 가능성 문장;
      } catch(CException e){
          CException 발생 시 실행 문장;
      }
  }
  ```

- 다중 `catch`

  - 일반적으로 많이 쓰임

  ```java
  void hello() throws Exception
  {
      try{
        AException 가능성 문장;
      	BException 가능성 문장;	
      	CException 가능성 문장;
      } catch(AException e){
          AException 발생 시 실행 문장;
      } catch(BException e){
          BException 발생 시 실행 문장;
      }	catch(CException e){
          CException 발생 시 실행 문장;
      }
  }
  ```

  - 다중 `catch` 사용 시 주의할 점

    - 부모 자식 클래스 정의하는 순서에 주의

    - 만약 `Exception`들이 상속관계를 갖는다면, 자식클래스에 대한 `catch`문을 먼저 정의해야함

    - ```java
      try{                                         
        1.ParentException 발생가능성 있는 문장;    
        2.ChildException 발생가능성 있는 문장;    
      }catch(ParentException pe){//pe=Parent;  pe=Child;
        System.out.println("ParentException!!");
      }catch(ChildException ce){
        System.out.println("ChildException!!");
      }
         
         catch에 선언한 클래스                       예외발생클래스
         ------------------------------------------
         ParentException pe = new ParentException();      <== 1번문장 예외 발생시
             ---> "ParentException!!"
         ParentException pe = new ChildException();       <== 2번문장 예외 발생시
             ---> "ParentException!!"
       ==========================================================================       
      try{
        1.ParentException 발생가능성 있는 문장;    
        2.ChildException 발생가능성 있는 문장;    
      }catch(ChildException ce){//ce = Parent; 일치하지 않음  ce=Child;
        System.out.println("ParentException!!");
      }catch(ParentException pe){
        System.out.println("ChildException!!");
      }
         
         catch에 선언한 클래스                       예외발생클래스
         ------------------------------------------
         ParentException pe = new ParentException();      <== 1번문장 예외 발생시
             ---> "ParentException!!"
         ChildException ce = new ChildException();       <== 2번문장 예외 발생시
             ---> "ChildException!!"
      ```

- `finally` 블럭

  ```java
  void hello() throws Exception
  {
      try{
          문장 1;	
      	문장 2;	// --> AEception 발생 가능성
      	문장 3;	
          문장 4;	// --> BException 발생 가능성
          문장 5;
      } catch(AException e){
          문장 6;
      } catch(BException e){
          문장 7;
      }
  }
  ```

  - 예외 발생 안했을 경우 : 1 - 2 - 3 - 4 - 5
  - AException 발생 : 1 - 6
  - BException 발생 : 1 - 2 - 3 - 7
  - 반드시 "문장 5"를 실행하고 싶다면? ==> `finally{}`

  ```java
  void hello() throws Exception
  {
      try{
          문장 1;	
      	문장 2;	// --> AEception 발생 가능성
      	문장 3;	
          문장 4;	// --> BException 발생 가능성
      } catch(AException e){
          문장 6;
      } catch(BException e){
          문장 7;
      }
      finally{
          문장 5;
      }
  }
  // * 참고 : try문 안에 return이 있어도, finally는 실행!
  ```

<br>

### 6) 예외 종류

- 체크(Checked) 예외

  - 컴파일 에러 발생
  - 명시적으로 발생할 수 있는 예외에 대한 처리를 강요
  - 반드시 `try ~ catch` 또는 `throws`를 사용해야 함

  ```java
  public static void main(String[] args){
      System.in.read();	// Unhandled exception type IOException
  }
  ```

  ```java
  new FileReader("a.txt");	// unhandled exception FileNotFoundException
  ```

- 언체크(UnChecked) 예외

  - 개발자 실수 또는 사용자 입력 데이터 예외
  - 컴파일 시 에러가 발생하지 않음
  - `RuntimeException`을 상속받는 예외
  - `try ~ catch` 또는 `throws` 사용 가능
  - `if`문을 통해서도 처리 가능

  ```java
  public static void main(String[] args){
      String []names = {"CHO", "KIM"};
      System.out.println(names[3]);	// RuntimeError
  }
  ```
  
- 다음 중 예외가 발생하는 문장은?

  ```java
  int a;
  void method(){
    int b;
    int c,d=0;
    System.out.println(a);  //멤버변수!!  0출력          
    System.out.println(b);  //error. 변수를 초기화하지 않았음
    System.out.println(c);  //error. 변수를 초기화하지 않았음
    System.out.println(d);  
  
    int e,f;
    if(su1<su2){ e=100; }
  
    if(조건식){ f=200; }
    else     { f=300; }
  
    System.out.println(e);  //error. 변수를 초기화하지 않았음
    System.out.println(f);  
  
    int g;
  
    try{
      g=400;
    }catch(예외클래스명 변수명){  }
  
    System.out.println(g);  //error. 변수를 초기화하지 않았음  
  }
  ```

<br>

### 7) 사용자정의 예외

- 일반적으로 예외의 발생은 JVM에 의해 실행중 발생

- 또한 사용자 프로그램에서 인위적으로 예외를 발생시킬 수 있음 ---> `throw` 문을 활용

  > throw 예외 객체;
  >
  > throw new 예외객체타입(매개변수);

  ```java
  class MyException extends Exception{
    public MyException(String msg){
      super(msg);
    }
  }
  ```

<br>

### 8) 오버라이딩 규칙

>
> class Parent{
>
>    접근제한자 void hello() throws A,B,C{
>
>   }
>
> }
>
> class Child extends Parent{
>
>    //오버라이딩 메소드
>     접근제한자 void hello() throws A,B,C{
>
>   }
>
> }

- 접근제한자는 부모와 동일하거나 확장해야 함

  - 부모  `public hello(){}`        	==> 자식   `public hello(){}`
  - 부모  `protected hello(){}`      ==> 자식   `protected/public hello(){}`
  - 부모  `hello(){}`                            ==> 자식   `(default)/protected/public hello(){}`

- `throws`는 부모와 동일하거나 축소해야 함

  ```java
  부모  public hello() throws AException, BException, CException{  }        
   
   [정상 오버라이딩 throws]
   ==> 자식   public hello() throws AException, BException, CException {  }
   ==> 자식   public hello() throws AException, BException {  }
   ==> 자식   public hello() throws AException {  }
   ==> 자식   public hello() {  }
   
   [에러 오버라이딩 throws]
   ==> 자식   public hello() throws AException, BException, CException ,DException{  }
   ==> 자식   public hello() throws Exception {  }
  ```

<br>

### ) Problems

